### ISSUE TITLE
Account creation flow implementation: Sign up

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-ios#353]
**Task**

Sign up flow for Account creation:

- [ ] Splash view
- [ ] New User/Existing User view
- [ ] Code view (will be used for invite or self sign up code later, but skipped for now)
- [ ] Connecting View (generate `seed`, connection to MQTT, subscription to `owner ok key` topics, publish to register and get balance, store response on owner record)
- [ ] Alias form view
- [ ] Profile Picture view
- [ ] Ready to use Sphinx -> Dashboard
